### ISSUE TITLE
Add functionality similar to pytest.mark

### ISSUE THREAD

**Issue by miloszbednarzak** [wntrblm/nox#339]
**How would this feature be useful?**
It can simplify filtering specific sessions to be run. It can simplify writing long commands like `nox -s tests, lint, type, ...`. It can also extend the functionality of `nox.options.sessions`.

**Describe the solution you'd like**
I have two ideas how this can be done.
Basically it can be run by: 
`nox -m [mark-name]` if feature called "Marks" as in pytest,
`nox -t [tag-name]` if feature called "Tags".
And nox will run only sessions annotated by this mark/tag.

**1st option**
In `noxfile.py` it can be configured either by:
```python
@nox.mark("mark_name")
@nox.session()
def ...
``` 
or
 ```python
@nox.tag("tag_name")
@nox.tag("other_tag_name")
@nox.session()
def ...
```

**2nd option**
```python
nox.options.tags = {
    "default": ["session1", "session2"],  # this might replace `nox.options.sessions`
    "tag1": ["session1", "session4"],
    "tag2": ["session2", "session3"],
    etc.
}
```

Personally I prefer the 2nd option, I think it makes it more clear and concise.
And also I prefer "Tags" over "Marks" name, IMO "Tags" more precisely describe what it is. On the other hand, "Marks" might be known for those who use pytest.

**Comment by DiddiLeija** [comment]
Hi! Is there any update? If not, I would like to help.

**Comment by DiddiLeija** [comment]
@theacodes @dhermes @cjolowicz Can I take care of this issue? If I can, tell me where to go.

**Comment by edgarrmondragon** [comment]
I'm interested in this feature 🙂 

@DiddiLeija If you have not started work on it yet, is it ok if I start a PR?

**Comment by DiddiLeija** [comment]
Yeah, actually I haven't started yet. You can go ahead if you want :)

**Comment by crwilcox** [comment]
Thanks for the offer @edgarrmondragon. I have assigned this to you just so folks know you are working on it. If that changes just let us know and we can unassign. This will be a super add!

**Comment by edgarrmondragon** [comment]
Awesome, thanks @crwilcox!

**Comment by edgarrmondragon** [comment]
I've started a (draft) PR: https://github.com/wntrblm/nox/pull/627
