### ISSUE TITLE
Enable ReadTheDocs builds for pull requests

### ISSUE THREAD

**Issue by DiddiLeija** [wntrblm/nox#497]
**How would this feature be useful?**

Sometimes, a pull request modifies the Nox documentation. But we cannot see how does the final document looks until the PR is merged.

**Describe the solution you'd like**

That one of the RTD project maintainers (@theacodes or @dhermes) enable this option on the settings. The reference about doing this can be found [here](https://docs.readthedocs.io/en/stable/pull-requests.html).

After that, each time the CI run, ReadTheDocs will build a separate documentation page to see how the document should look like. It dissappears after 90 days since the PR is merged. However, this feature has some [limitations](https://docs.readthedocs.io/en/stable/pull-requests.html#limitations).

**Describe alternatives you've considered**

Keep without these builds, so we'll have to run the builds locally, or just guess how the document should be.

**Comment by FollowTheProcess** [comment]
@DiddiLeija If you run `nox -s docs` locally it will build the docs and automatically serve them up in the default web browser for exactly this reason! 👍🏻 

It also watches files for changes so if you edit the docs, you can see the output live in your browser window.

**Comment by DiddiLeija** [comment]
That's true (I run `nox -s docs` when I want to see the docs, and that's just great). But sometimes (specially when I only use the browser without a Git clone), it would be fine to see the final product on ReadTheDocs.

**Comment by cjolowicz** [comment]
FWIW I counted 5 PRs with docs changes in 2021.10.1, out of a total 18. For 2021.6.6 it was 7 out of 28 PRs.

**Comment by theacodes** [comment]
Even though I'm paying to support RTD, I also feel like this is unnecessary
for us. That's not a "no, never" that's a "not right now".
