### ISSUE TITLE
Remove usage of py.path?

### ISSUE THREAD

**Issue by henryiii** [wntrblm/nox#583]
Currently, there is a dependency on `py.path`, which pytest is trying to remove, and it seems like nox should remove it too, now that Python 3 is required (since quite a while, actually). py.path is not recommended for use: https://py.readthedocs.io/en/latest/path.html. This would reduce a dependency, too!

Looking through the usages, I see `py.path.local.sysfind`, which with a little effort could be replaced by Python 3's [shutil.which](https://docs.python.org/3/library/shutil.html#shutil.which). I see `as_cwd`, which could be handled pretty easily (ideally looking like the [3.11 context addition](https://docs.python.org/3.11/library/contextlib.html#contextlib.chdir)). That seems to be it for non-test usages.

**Comment by henryiii** [comment]
Would you like me to take a stab at it?

**Comment by DiddiLeija** [comment]
Sounds good to me :+1:

**Comment by FollowTheProcess** [comment]
Great idea! 🎉

**Comment by henryiii** [comment]
FYI, removing it is really easy, but untangling the monkey patched unittests is not (though I love the test granularity that allows, so not against it, just extra work for this sort of a change). I should be able to finish it up later in the week.
