### ISSUE TITLE
Provide labels at issue templates?

### ISSUE THREAD

**Issue by DiddiLeija** [wntrblm/nox#585]
**How would this feature be useful?**

Currently, when a user creates an issue, it doesn't has labels. Maybe we can alleviate the maintainer's work by automating the labels addition.

**Describe the solution you'd like**

Add labels to the issue templates: `bug` at the bug template and `enhancement` at the feature request, maybe?

**Describe alternatives you've considered**

If we keep as is, it's ok for me too :+1:

**Comment by FollowTheProcess** [comment]
I think this could be done (plus some more nice improvements) with the new GitHub issue yaml forms https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms.

I've got them set up on most of my projects and they work great! See some examples [here](https://github.com/FollowTheProcess/pytoil/issues). I also have it set up with [release drafter](https://github.com/marketplace/actions/release-drafter) and an [auto-labeller](https://github.com/crazy-max/ghaction-github-labeler) which actually thinking about it I'm not 100% sure I need anymore if the issue template sets labels

**Comment by DiddiLeija** [comment]
> I think this could be done (plus some more nice improvements) with the new GitHub issue yaml forms

I think a switch to these new templates is a great idea too!
