### ISSUE TITLE
nox hangs at interactive terminal when python interpreter is specified for session

### ISSUE THREAD

**Issue by DragonAxe** [wntrblm/nox#602]
# System info
Platform Windows 10 Pro

Installed python versions:
```
$ py -0
Installed Pythons found by C:\WINDOWS\py.exe Launcher for Windows
 -3.9-64 *
```
`nox` installed via pip:
```
$ nox --version
2022.1.7
```
Project is an empty folder containing only a noxfile.py:
```
# noxfile.py
import nox

@nox.session(python=['python3.9', 'python3.8'])
def some_task(session):
    print("Here")
```

# Symptoms
When running `nox` with the noxfile.py specified above, `nox` hangs until I type `ctrl+z` and `Enter` shown as `^Z` in the terminal output below:
```
$ nox
nox > Running session some_task-python3.9
^Z
nox > Session some_task-python3.9 skipped: Python interpreter python3.9 not found.
nox > Running session some_task-python3.8
^Z
nox > Session some_task-python3.8 skipped: Python interpreter python3.8 not found.
nox > Ran multiple sessions:
nox > * some_task-python3.9: skipped
nox > * some_task-python3.8: skipped
```
Removing `python=['python3.9', 'python3.8']` from the nox file works correctly:
```
$ nox
nox > Running session some_task
nox > Creating virtual environment (virtualenv) using python.exe in .nox\some_task
Here
nox > Session some_task was successful.
```
While `nox` is hanging, the task manager shows 2 `python` processes (EDIT: and one `py` process):
```
"C:\Program Files\Python39\python.exe" "C:\Users\username\AppData\Roaming\Python\Python39\Scripts\nox.exe"
"C:\Program Files\Python39\python.exe" - -c "import sys; print(sys.executable)"
C\WINDOWS\py.EXE - -c "import sys; print(sys.executable)"
```
When I execute the second command, I am entered into a python interactive terminal
```
$ "C:\Program Files\Python39\python.exe" - -c "import sys; print(sys.executable)"
Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by DiddiLeija** [comment]
Just to start (and remove a possible false-positive report), from what I can tell from [the docs](https://nox.thea.codes/en/stable/config.html#configuring-a-session-s-virtualenv) and (as far as I know) and also [this function](https://github.com/wntrblm/nox/blob/f3adccbb8ab377638786b11cb754a04a9e613132/nox/virtualenv.py#L93), doing `python=["python-3.9"]` is invalid, but `python=["3.9"]` should work fine.

**Comment by DragonAxe** [comment]
Yes, using `python=['3.9', '3.8']` works correctly. I must have gotten `python-3.9` from tox-to-nox.
Is there a better way `nox` can handle this invalid case? Perhaps throw an error before `py` is invoked?
