### ISSUE TITLE
Add a single character shortcut for --no-reuse-existing-virtualenvs

### ISSUE THREAD

**Issue by johnthagen** [wntrblm/nox#624]
### How would this feature be useful?

A common way to use Nox that saves a lot of time when re-running sessions over and over by avoiding recreating venvs is to set:

```py
nox.options.reuse_existing_virtualenvs = True
```

You can see the `pip` developers use this:

- https://github.com/pypa/pip/blob/main/noxfile.py#L19

When dependencies _do_ change, the developer can then run:

```
nox --no-reuse-existing-virtualenvs -s test
```

Given this can be a very common work flow, avoiding having to type out `--no-reuse-existing-virtualenvs` on the command line would be a great improvement to UX.

### A note on `tox`

What I'm describing above is also the default workflow for `tox` users. Many people moving from `tox` will be familiar with this workflow. (e.g. `tox` re-uses venvs by default, and `tox -r` is an opt-in recreation).

### Describe the solution you'd like

Add a new alias for `--no-reuse-existing-virtualenvs`, for example `-C` for "Create"

```
nox -C -s test
```

**Comment by johnthagen** [comment]
Related to #488

**Comment by ktbarrett** [comment]
The CLI supports multicharacter short options and does not currently use `-n` (which would cause ambiguity), so it may be possible to use the more intuitive `-nr` short option.

**Comment by johnthagen** [comment]
`-nr` would also be a suitable fix for this if the team agrees.

**Comment by DiddiLeija** [comment]
I don't see any blockers to do this. Any thoughts @wntrblm/nox?

**Comment by crwilcox** [comment]
By default environments are destroyed and recreated, so wouldn't this be a noop?

**Comment by johnthagen** [comment]
@crwilcox Not if the user has set in their `noxfile.py`:

```py
nox.options.reuse_existing_virtualenvs = True
```

**Comment by crwilcox** [comment]
Alright. So, to me this sort of feels like an antipattern, but since we already have the  long flag, I'd be okay with adding -nr.

**Comment by johnthagen** [comment]
> I don't know how prevalent setting args in noxfile.py really is, but as it is allowed, that might not be that relevant 

The `pip` developers seem to like them 😄 

- https://github.com/pypa/pip/blob/main/noxfile.py#L19
