### ISSUE TITLE
Missing action_helper in PyPI tarball

### ISSUE THREAD

**Issue by frenzymadness** [wntrblm/nox#644]
### Current Behavior

In PyPI tarball, there is `test_action_helper.py` module but the module this one should test (`.github/action_helper.py`) is not there.

### Expected Behavior

I think that the tarball should either contain both files or neither of them.

### Steps To Reproduce

1. Download and unpack the tarball.
2. Run tests.

### Environment

```Markdown
Does not matter
```

**Comment by DiddiLeija** [comment]
I found both files...

I first decompressed the tarball, then looked for both files, and I found them (both `.github/action_helper.py` and `tests/test_action_helper.py`).

However, I haven't tried to run the tests yet.

**Comment by DiddiLeija** [comment]
Oh no, you're right, the PyPI tarball (from https://pypi.org/project/nox/#files) does not contain the `.github` section. However, the GitHub tarball does :man_shrugging:.

**Comment by frenzymadness** [comment]
Yes, github tarball contains everything from the repo. PyPI tarballs contain only what is included by the build system - so the files are either identified or specified in pyproject.toml or manually included in tarball via MANIFEST.in.

To fix this inconsistency, we can either include the action_helper.py into PyPI tarball via MANIFEST.in or use the same file for excluding the test_action_helper.py.

**Comment by DiddiLeija** [comment]
> To fix this inconsistency, we can either include the action_helper.py into PyPI tarball via MANIFEST.in or use the same file for excluding the test_action_helper.py.

cc @wntrblm/nox
