### ISSUE TITLE
Add a `default=True` argument to nox.session

### ISSUE THREAD

**Issue by Julian** [wntrblm/nox#654]
### How would this feature be useful?

I'd like to write

```python
@nox.session
def bar():
    pass

@nox.session(default=False)
def foo():
    pass

@nox.session
def baz():
    pass
```

as a DRYer alternative to:

```python
nox.options.sessions = ["bar", "baz"]

@nox.session
def bar():
    pass

@nox.session
def foo():
    pass

@nox.session
def baz():
    pass
```

i.e. to be able to specify whether a session is run by default or not when defining it, rather than hardcoding the sessions that should be run.

Has this been considered before perhaps?

### Describe the solution you'd like

Programmatically build up `nox.options.sessions` unless it's defined explicitly via the addition of a parameter (defaulting to True to match the current behavior) which defines whether a session is run by default or not.

### Describe alternatives you've considered

Obviously there could be some noodling on what to call the parameter.

**Comment by DiddiLeija** [comment]
Sounds good to me! Using a parameter (instead of a variable) could be more human-readable, maybe?

Any thoughts from the maintainers?

**Comment by rnickle** [comment]
It looks like this was brought up before and closed in #232.  It was also discussed in #40, which was closed in favor of #141. 

The _nox.options_ implementation of _nox.options.sessions_ was the solution adopted.

**Comment by Julian** [comment]
Fair enough, if there isn't a desire to add this obviously feel free to close -- I've basically started copy pasting [this](https://github.com/python-jsonschema/referencing/blob/c1a9ce8693d67b7b79a691e1bd0c4df1b73f617f/noxfile.py#L11-L20) into all my noxfiles which I'm happy to keep doing if others don't need this.

**Comment by 12rambau** [comment]
I would be very interested by this functionality. Just to give you a use case, we manage the translation of our Sphinx theme with Babel. update and compilation is managed by a nox session and a 2nd one is used to add extra languages. we would like to exclude the "init_language" from the default.

**Comment by JayBazuzi** [comment]
I would love this for autopep8.

I have a flake8 session that I want to run by default. If I could, I would make an autopep8 session that was skipped by default, and then `nox -s autopep8` to fix most reported errors.

(Or `black --check` / `black`)

Another use would be a session to run `pip freeze > constraints.txt`.

**Comment by MicaelJarniac** [comment]
I'd also really like something like this.

I'm currently experimenting with the following:
```py
import nox
skip = {"foobar"}
# Needs to go at the bottom of `noxfile.py`:
nox.options.sessions = [key for key in nox.registry.get() if key not in skip]
```
Which isn't perfect, but might do the trick in some cases.

I was also thinking about writing my own custom decorators, like an `@skip` and/or an `@only`, to throw above `@nox.session`, that'd manage including or excluding sessions by default.
