### ISSUE TITLE
Compatibility with tox 4

### ISSUE THREAD

**Issue by frenzymadness** [wntrblm/nox#673]
### Current Behavior

Tox 4 is now in release candidate 1 and it might make sense to take a look at how to support it here in tox_to_nox. Right now, tests results are:

```
FAILED tests/test_tox_to_nox.py::test_trivial - AttributeError: module 'tox.c...
FAILED tests/test_tox_to_nox.py::test_skipinstall - AttributeError: module 't...
FAILED tests/test_tox_to_nox.py::test_usedevelop - AttributeError: module 'to...
FAILED tests/test_tox_to_nox.py::test_commands - AttributeError: module 'tox....
FAILED tests/test_tox_to_nox.py::test_deps - AttributeError: module 'tox.conf...
FAILED tests/test_tox_to_nox.py::test_env - AttributeError: module 'tox.confi...
FAILED tests/test_tox_to_nox.py::test_chdir - AttributeError: module 'tox.con...
FAILED tests/test_tox_to_nox.py::test_dash_in_envname - AttributeError: modul...
FAILED tests/test_tox_to_nox.py::test_non_identifier_in_envname - AttributeEr...
FAILED tests/test_tox_to_nox.py::test_descriptions_into_docstrings - Attribut...
```

All failures caused by

```
def main() -> None:
        parser = argparse.ArgumentParser(description="Converts toxfiles to noxfiles.")
        parser.add_argument("--output", default="noxfile.py")
    
        args = parser.parse_args()
    
>       config = tox.config.parseconfig([])
E       AttributeError: module 'tox.config' has no attribute 'parseconfig'
```

### Expected Behavior

It would be nice to have nox compatible with tox 4 when they release a final version.

### Steps To Reproduce

Run nox tests with tox==4.0.0rc1

### Environment

```Markdown
- OS:
- Python:
- Nox:
```

**Comment by FollowTheProcess** [comment]
This is definitely something we'd like to continue to support. I've just had a little poke around `4.0.0rc1` and can't see an equivalent way of Nox loading the tox config file, admittedly I only did a quick scan.

It's worth looking into how we'd do this before deciding how to proceed

**Comment by FollowTheProcess** [comment]
So it turns out there is no supported way of parsing the tox config in version 4 that we can use. See the [discussion](https://discuss.python.org/t/tool-tox-4-on-the-horizon/6537/29?u=followtheprocess).

Looks like the best we can do is:

- Detect which tox version is installed at runtime
- If <4 then use the current parsing method
- If >=4 then we'll have to do something else, e.g. parse the CLI output as suggested in the discussion above
