### ISSUE TITLE
Add option to skip session by default

### ISSUE THREAD

**Issue by slavong** [wntrblm/nox#686]
# How would this feature be useful?

Currently nox supports the possibility to exclude some sessions from running by default using positive list `nox.options.sessions = [session1, session3]`. In this case session2 would not be executed by running `nox` and would need to be specified explicitly, e.g. `nox -s session2`

# Describe the solution you'd like

Usually, this kind of tagging is expected to be found in negative lists. If someone forgets to add the session4 to the `nox.options.sessions` list, then it would run by default.

My proposal is to add an option to `nox.sessions` to skip the session by default
```
@nox.session(skip=True)
def session2(session):
   pass
```

# Describe alternatives you've considered
Writing my own decorator would be an option, but a built-in solution would be preferrable.

# Anything else?
No response

**Comment by rnickle** [comment]
@slavong, perhaps this issue could be merged with a similar suggestion in #654?

**Comment by lhupfeldt** [comment]
> as using `nox.options.sessions` is quite cumbersome.
I completely agree with this. I think excluding a single (or few) sessions from the default is far more useful, and less error prone (the serious error being test **not** run by mistake) than maintaining a positive list of sessions.
