### ISSUE TITLE
does nox support testing built wheel files?

### ISSUE THREAD

**Issue by jbiz25** [wntrblm/nox#692]
### How would this feature be useful?

 It is really important to me that the wheel files are the things that actually get tested, since I am including some cythonized C extensions.

### Describe the solution you'd like

I am not sure if I am abusing nox, but I am trying to use it to test my built wheel files across Python versions. But, it seems as though nox always uses my project's source code, rather than the built wheel. I use nox to automatically install the wheel into a session, but after close examination, seems like the wheel isn't what is actually being tested. I am using pytest. The tests reside in the project's top-level folder, at the same level as my noxfile.

### Describe alternatives you've considered

Some other automation tool, as yet to be chosen.

**Comment by FollowTheProcess** [comment]
I think you'd have to have an explicit nox session to build your wheel (include the tests using whatever build tool you prefer) then install from that wheel and run the tests? Not 100% sure though as I've never had to do this but I think that's the basic flow

**Comment by jbiz25** [comment]
Yes, that's what I have tried.  I created a build session that builds the wheel.  That works.  Then the next session that runs installs the wheel and runs the tests.  However, somehow it seems the tests are still using my project's source code, and not the wheel.

**Comment by crwilcox** [comment]
@jbiz25 I do this for a project of mine, https://github.com/googleapis/python-crc32c. You can likely mirror the approach.

**Comment by jbiz25** [comment]
thanks @crwilcox  .  There looks like there are a bunch of similarities between what you and I are doing.  In fact, I thought my nox setup was working until my nox pytests missed a blatant error with the compiled version of my wheel.  I too have a python-only version of my code (in my source code) but my wheel has several modules which get compiled by Cython.  I discovered that nox was using my source code, not my wheel's compiled Cython code.  Then, I wrote a simple test to check the extension of a file and sure enough, during nox testing, the extension was .py, but it should be .pyd.  That particular .py file doesn't exist in my compiled wheel.  That's how I doscovered nox was using something other than my compiled wheel to test.  I will study your exmaple more closely though to see if there's a difference.  It seems nox is either using my sdist or my project source code directory instead of my bdist.

**Comment by jbiz25** [comment]
FYI, I was able to fix my problem by switching my project to a src layout.  I actually owe it to nox for helping me uncover a problem with with testing flow!  I just thought nox was doing something magical behind the scenes that I didn't understand.
