### ISSUE TITLE
Detect session.install('pip'....) with `--no-install`

### ISSUE THREAD

**Issue by q0w** [wntrblm/nox#693]
### How would this feature be useful?

I want to use `--no-venv` and `--no-install` so I need to rewrite all `session.install` with `session.run('pip'...)` but nox does not detect that and runs the installation process.

### Describe the solution you'd like

Detect session.install args and check if `--no-install` arg is provided

**Comment by theacodes** [comment]
You want Nox to error on `session.run('pip'...)` when `--no-install` is specified? That's kind of the explicit escape hatch for that, so I'm hesitant to overreach there.

**Comment by cjolowicz** [comment]
You can use session.run_always which will be skipped under --no-install.

Despite the (somewhat misleading) name, it's the API to run installation-phase commands that don't implicitly use pip install.

**Comment by henryiii** [comment]
This was fixed by renaming run_always.
