### ISSUE TITLE
time_of_day(12) returns ""

### ISSUE THREAD

**Issue by aglet** [wntrblm/nox#697]
For the hour following noon, I'd expect `time_of_day()` to return "afternoon"; instead I got "". I tried fixing this as follows, but was unsuccessful in getting the test suite to run:

```diff
@@ -41,7 +41,7 @@ def time_of_day(hour: int) -> str:
     """Given current hour, returns time of the day."""
     if 0 < hour < 12:
         return _("morning")
-    elif 12 < hour <= 18:
+    elif 12 <= hour <= 18:
         return _("afternoon")
     elif 18 < hour <= 23:
         return _("evening")
```

**Comment by Julian** [comment]
I assume this was filed in the wrong place? Probably you meant to file it on https://github.com/staticdev/human-readable
