### ISSUE TITLE
Support argcomplete v3.0

### ISSUE THREAD

**Issue by zachliu** [wntrblm/nox#698]
### How would this feature be useful?

Version 3.0.0 of [argcomplete](https://github.com/kislyuk/argcomplete/releases) is out, yet nox limits the version it depends on to <3. Please support argcomplete v3.0 so that users can use the latest versions of all involved packages. Thanks!

**Comment by reaperhulk** [comment]
This is done in https://github.com/wntrblm/nox/pull/700 😄
