### ISSUE TITLE
`run_installer` as an alias to `run_always`

### ISSUE THREAD

**Issue by MicaelJarniac** [wntrblm/nox#711]
### How would this feature be useful?

`run_always` has a misleading name.

| Flag             | `run` | `run_always` |
|------------------|:-----:|:------------:|
| No flag          | ✅    | ✅           |
| `-R`             | ✅    | ❌           |
| `--install-only` | ❌    | ✅           |

It doesn't "always run", as the name implies.

### Describe the solution you'd like

Add an alias to `session.run_always`, like `session.run_installer`, that makes it clear that it's meant to be used to run commands to install things. This would make sense with its current behavior of not running with `-R`.

This could then become the recommended method, and `run_always` could be kept for backward compatibility.

**Comment by cjolowicz** [comment]
Fixed in #770
