### ISSUE TITLE
Save session name in `Func`

### ISSUE THREAD

**Issue by MicaelJarniac** [wntrblm/nox#717]
### How would this feature be useful?

The session name manually provided at `@nox.session(name="foo")` does get sent to `nox._decorators.Func(name="foo")`, but it's then ignored, and not saved to the instance.

Also, if the session name isn't manually provided, it'll be inferred from the function name, but then won't even be sent to `Func`.

https://github.com/wntrblm/nox/blob/720f1ea538bbf7ceb7fad3eafaf662437a7183e7/nox/_decorators.py#L60

https://github.com/wntrblm/nox/blob/720f1ea538bbf7ceb7fad3eafaf662437a7183e7/nox/registry.py#L88-L89

Saving the session name, be it manually provided or automatically inferred, would make it easier for other developers to extend Nox functionality with other libraries.

### Describe the solution you'd like

I'd like for the session name, regardless of whether it was manually provided, to be sent to `Func` and saved as an instance variable there.

### Anything else?

I believe this is a simple and quick enough change, so I'll be sending a PR with a possible implementation.

**Comment by cjolowicz** [comment]
`Func` is not part of Nox's public API. Can you not use `session.name` here?

**Comment by MicaelJarniac** [comment]
> `Func` is not part of Nox's public API. Can you not use [session.name](https://nox.thea.codes/en/stable/config.html#nox.sessions.Session.name) here?

How can I get to `session.name` from outside a session function?

What I wanted to do was to get all session names, so I could filter them and assign them to `nox.options.sessions`.

What I ended up doing was getting them from `nox.registry.get()`.

If I understood it correctly, though, `@nox.session` returns a `Func` instance, and not the function itself, so if `Func().name` was present, I could simply do something like:

```py
import nox

@nox.session(name="bar")
def foo():
    pass

assert foo.name == "bar"
```

This might be a bit cursed, but it would allow me to easily define functions to skip by simply using references to them, without using strings.
