### ISSUE TITLE
GitHub Action missing Python 3.12

### ISSUE THREAD

**Issue by brettcannon** [wntrblm/nox#742]
### Current Behavior

I can't use the GitHub Action to run tests via nox against Python 3.12 as it isn't included.

### Expected Behavior

To be able to use Python 3.12.

### Steps To Reproduce

https://github.com/brettcannon/microvenv/actions/runs/6490071439/job/17625324059?pr=55#step:4:98

### Environment

```Markdown
- OS:
- Python:
- Nox: included via GitHub Actions
```

**Comment by DiddiLeija** [comment]
I believe it's safe (and fair) to add Python 3.12, since it's now a stable version.
I've opened #743, which should resolve the issue.
