### ISSUE TITLE
`session.run` does not fail gracefully when receiving a list as command to run

### ISSUE THREAD

**Issue by stefanv** [wntrblm/nox#746]
### Current Behavior

`session.run(["pytests", "mypkg"])` results in a traceback.

### Expected Behavior

One of the following options:

(a) The error is caught and a helpful message displayed.
(b) The list is correctly intepreted as a command.

### Steps To Reproduce

```python
import nox


@nox.session
def tests(session: nox.Session) -> None:
    session.run(["pytest", "foo"])
```

### Environment

```Markdown
- OS: Linux
- Python: 3.11
- Nox: 2023.4.22
```

### Anything else?

I would be happy to submit a PR to address the issue, once I know which solution is preferred.

**Comment by henryiii** [comment]
IMO a) is fine, it keeps the syntax and type hints simple, and you simply need to add a single character (`*`) to convert if you already have a list.
