### ISSUE TITLE
Support an environment variable override for `nox.options.default_venv_backend`

### ISSUE THREAD

**Issue by edgarrmondragon** [wntrblm/nox#776]
### How would this feature be useful?

Often times it's easier to set an environment variable than passing the same argument to multiple commands.

### Describe the solution you'd like

A new environment variable that's used as the default value of `--default-venv-backend` when present.

Some possible names: `NOX_DEFAULT_VENV_BACKEND` or `NOXDEFAULTVENVBACKEND`

### Describe alternatives you've considered

Something like

```python
# noxfile.py

import os

import nox

nox.options.default_venv_backend = os.environ.get("NOX_DEFAULT_VENV_BACKEND", "virtualenv")
```

### Anything else?

If this accepted, I can start working on a PR :)

**Comment by henryiii** [comment]
`NOX_DEFAULT_VENV_BACKEND` sounds good to me.
