### ISSUE TITLE
Publish new release to PyPI

### ISSUE THREAD

**Issue by johnthagen** [wntrblm/nox#788]
[The last release of nox was almost a year ago](https://pypi.org/project/nox/2023.4.22/#history). Would it be possible to release a new version so that the community can take advantage of all of the improvements that have been added since then? ❤️

**Comment by cjolowicz** [comment]
see #789

**Comment by johnthagen** [comment]
GitHub release is complete, only remaining step is publishing to PyPI

- https://github.com/wntrblm/nox/pull/789#issuecomment-1974959156

**Comment by cjolowicz** [comment]
Published!

**Comment by johnthagen** [comment]
@cjolowicz @theacodes One thing I noticed is that the _latest_ docs actually point to the older version?

- https://nox.thea.codes/en/latest/CHANGELOG.html

<img width="572" alt="Screenshot 2024-03-06 at 10 44 49 AM" src="https://github.com/wntrblm/nox/assets/10340167/68c435f5-604c-4930-bf11-ab3a17d3cfaa">

**Comment by theacodes** [comment]
Not sure why ReadTheDocs missed that, I just manually triggered the build and it did its thing. :)

**Comment by cjolowicz** [comment]
FWIW I also had to trigger the stable build after the tag was pushed. Maybe we need to redeploy the webhook (or something).
