### ISSUE TITLE
Next version plans

### ISSUE THREAD

**Issue by henryiii** [wntrblm/nox#860]
Around Python 3.13 release day (~~Tuesday~~ I mean Monday) I'd like a release of Nox to get Python 3.13 by default in the action (and that Python 3.13 classifier!). There are a few PRs that maybe could go in - I have a little helper (#847) that needs some feedback (is it a good name, a good idea, etc). Happy to have it wait, though. I think #631 would be interesting to get a bit of feedback[^1], but it should be in main for a while, so not a target for this release. I also have a few ci and fix PRs I can get in before Tuesday, like dropping pypy-3.9 from the action defaults.

Current contents of the release:

```md
* feat: allow setting tags on parametrized sessions by @living180 in https://github.com/wntrblm/nox/pull/832
* feat: support for uv-installed pythons by @saucoide in https://github.com/wntrblm/nox/pull/842
* fix(types): Update type annotation of `stderr` parameter to make it optional by @edgarrmondragon in https://github.com/wntrblm/nox/pull/835
* chore(ci): use default action tests for macos-14 by @mayeut in https://github.com/wntrblm/nox/pull/824
* chore: add 3.13 to the action defaults by @henryiii in https://github.com/wntrblm/nox/pull/846
* chore: drop Python 3.7 by @henryiii in https://github.com/wntrblm/nox/pull/822
* chore: include 3.13 in classifiers by @henryiii in https://github.com/wntrblm/nox/pull/851
* chore: use uv if available in action by @henryiii in https://github.com/wntrblm/nox/pull/831
* ci: Test with Python 3.13 by @edgarrmondragon in https://github.com/wntrblm/nox/pull/834
* ci: macos-latest now is macos-14 by @henryiii in https://github.com/wntrblm/nox/pull/821
* ci: use miniforge by @henryiii in https://github.com/wntrblm/nox/pull/854
* docs: add warning about uv and local packages by @henryiii in https://github.com/wntrblm/nox/pull/830
* docs: fix contribution guidelines by @Wurstnase in https://github.com/wntrblm/nox/pull/850
* docs: Fix typos by @ember91 in https://github.com/wntrblm/nox/pull/839
* docs: Typo-fix in Cookbook by @hmd101 in https://github.com/wntrblm/nox/pull/837
* docs: add missing cookbook recipe snippet imports by @KasperZutterman in https://github.com/wntrblm/nox/pull/853
```

Should go in:

- #859
- #858
- #856
- Docs updates: cookbook (see #857) & touch up uv suggestions (astral-sh setup-uv mention, `--reinstall-package` for `.` - see #840)

Maybe, pending review:

- #847

[^1]: Longer term, if someone wants to look over https://github.com/wntrblm/nox/pull/631#issuecomment-2342070934 - would be appreciated :)

**Comment by DiddiLeija** [comment]
Thanks for all the work @henryiii!

Anything else you would like to get done before cutting a release? :)

**Comment by henryiii** [comment]
That was it. :) I wanna have a little time for the symlink fix, to make sure we don’t make the wrong fix.

**Comment by henryiii** [comment]
I think @theacodes is planning to do the release soon. :)

**Comment by theacodes** [comment]
Just to be clear - y'all are ready for me to cut a release?

**Comment by henryiii** [comment]
Yep. :)

**Comment by DiddiLeija** [comment]
Fine with me! :)

**Comment by theacodes** [comment]
It's released! :) Thank you, everyone!
