### ISSUE TITLE
Nox fails to recognize UV installed Python versions

### ISSUE THREAD

**Issue by Rastow** [wntrblm/nox#885]
### Current Behavior

Hello everybody,
I am using nox with PDM, which I installed using UV. When running tests on multiple Python versions, the sessions fail for all versions, which are not installed system wide. I noticed UV installs the missing python versions, but they are not available in the terminal when using `py --list` and so nox cannot create the virtualenv.

### Expected Behavior

I would expect nox to use the Python versions installed by UV or at least skip the sessions with missing interpreters instead of failing.

### Steps To Reproduce

1. Install UV via powershell
2. Install PDM and nox using uv tool install
3. Run nox in the project directory

### Environment

```Markdown
- OS: Windows 10 Home
- Python: 3.12.7
- Nox: 2024.10.9
- UV: 0.4.30
- PDM: 2.20.0.post1
```

### Anything else?

noxfile.py
```python
import os

import nox


nox.needs_version = ">=2024.10.9"
os.environ.update({"PDM_IGNORE_SAVED_PYTHON": "1"})
PYTHON_VERSIONS = ["3.10", "3.11", "3.12", "3.13"]


@nox.session(python=PYTHON_VERSIONS, reuse_venv=True)
def tests(session: nox.Session) -> None:
    session.run_always("pdm", "install", "-G", "test", external=True)
    session.run("pytest")

```

powershell output
```
PS D:\Robert\Documents\PycharmProjects\example> nox
nox > Running session tests-3.10
nox > Creating virtual environment (virtualenv) using python3.10 in .nox\tests-3-10
nox > Command C:\Users\Robert\AppData\Roaming\uv\tools\nox\Scripts\python.exe -m virtualenv 'D:\Robert\Documents\PycharmProjects\example\.nox\tests-3-10' -p python3.10 failed with exit code 1:
Exception in thread Thread-2 (_readerthread):
Traceback (most recent call last):
  File "c:\users\robert\appdata\local\programs\python\python312\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "c:\users\robert\appdata\local\programs\python\python312\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\robert\appdata\local\programs\python\python312\Lib\subprocess.py", line 1599, in _readerthread
    buffer.append(fh.read())
                  ^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 38: invalid start byte
Exception in thread Thread-4 (_readerthread):
Traceback (most recent call last):
  File "c:\users\robert\appdata\local\programs\python\python312\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "c:\users\robert\appdata\local\programs\python\python312\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\robert\appdata\local\programs\python\python312\Lib\subprocess.py", line 1599, in _readerthread
    buffer.append(fh.read())
                  ^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 38: invalid start byte
RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.10'
nox > Session tests-3.10 failed.
```

uv python directory
```
PS C:\Users\Robert\AppData\Roaming\uv\python> ls


    Verzeichnis: C:\Users\Robert\AppData\Roaming\uv\python


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        07.11.2024     00:46                .cache
d-----        07.11.2024     00:44                cpython-3.10.15-windows-x86_64-none
d-----        07.11.2024     00:45                cpython-3.11.10-windows-x86_64-none
d-----        07.11.2024     00:45                cpython-3.12.7-windows-x86_64-none
d-----        07.11.2024     00:46                cpython-3.13.0-windows-x86_64-none
-a----        07.11.2024     00:44              1 .gitignore
-a----        07.11.2024     11:11              0 .lock
```

Thank you for your time and help!

**Comment by leodevian** [comment]
Try installing `nox[uv]` instead of `nox`.

```shell
uv tool install "nox[uv]"
```

**Comment by henryiii** [comment]
It should be using uv installed Pythons if you are using the uv bakcend. Something is wrong with paths. It's trying to open something that isn't valid.

I think you are using the default virtualenv backed, could you try using the uv one?

**Comment by henryiii** [comment]
And does this command fail by itself?

```
C:\Users\Robert\AppData\Roaming\uv\tools\nox\Scripts\python.exe -m virtualenv 'D:\Robert\Documents\PycharmProjects\example\.nox\tests-3-10' -p python3.10
```

**Comment by Rastow** [comment]
> It should be using uv installed Pythons if you are using the uv bakcend. Something is wrong with paths. It's trying to open something that isn't valid.
> 
> I think you are using the default virtualenv backed, could you try using the uv one?

All sessions suceed when using the `uv` backend. That's great!
`nox.options.default_venv_backend = "uv"`

> And does this command fail by itself?
> 
> ```
> C:\Users\Robert\AppData\Roaming\uv\tools\nox\Scripts\python.exe -m virtualenv 'D:\Robert\Documents\PycharmProjects\example\.nox\tests-3-10' -p python3.10
> ```

However, this command fails with the message `RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.10'`.

**Comment by henryiii** [comment]
> However, this command fails with the message

That's why nox is failing. virtualenv doesn't know how to find the uv Python. But uv does.

**Comment by Rastow** [comment]
I'm still confused about one aspect though. In the [documentation](https://nox.thea.codes/en/stable/usage.html#failing-sessions-when-the-interpreter-is-missing) it says sessions are skipped when the interpreter is missing. However, `nox` unexpectedly installs missing Python interpreters using `uv` and then the sessions fail because `virtualenv` cannot find them. I did not expect this, and adding `nox.options.default_venv_backend = "uv"` seems like a strange fix, as other users of my package may not have installed `uv`. Maybe I am misunderstanding something here..

**Comment by henryiii** [comment]
You can set `nox.options.default_venv_backend = "uv|virtualenv"`, which will fall back if uv is not present. I set that on all my noxfiles since it's much faster if uv is installed. We should only be trying to install Pythons if uv is used, so this is likely a bug, and we also need some controls for the behavior (which someone said they'd work on when they have time).

**Comment by Rastow** [comment]
Okey, I'll close this issue as the sessions now run and it makes sense to use `uv` if it is present, while falling back to `virtualenv` if it cannot be found. Thank you for clarifying!
